trigger:
  branches:
    include:
    - main
  paths:
    include:
    - projects/monitoring-AC-UAEN-SharedServices-PR-001.bicep
    - projects/monitoring-rg-uae-printservices-001.bicep
    - projects/monitoring-rg-AvayaAura-pp-001.bicep
    - projects/monitoring-rg-menanettest-ts-001.bicep
    - projects/monitoring-rg-uaen-tempprint-ts-001.bicep
    - modules/scheduled_query_rules.bicep

name: Deploy Log Query Alert Rules in subscription_2 Subscription

variables:
  vmImageName: 'ubuntu-latest'
  azureServiceConnection: 'Customer-Service-Connection'
  subscriptionId: '54321'
  location: 'UAE North'
  system.debug: true

pool:
  vmImage: $(vmImageName)

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: Create/Update Log Query Alert Rules in rg-UAEN-ActiveDirectory-PR-001
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    subscriptionId: '$(subscriptionId)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-UAEN-ActiveDirectory-PR-001'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/projects/monitoring-rg-UAEN-ActiveDirectory-PR-001.bicep'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployBicepFile'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Create/Update Log Query Alert Rules in rg-uae-printservices-001
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    subscriptionId: '$(subscriptionId)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-uae-printservices-001'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/projects/monitoring-rg-uae-printservices-001.bicep'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployBicepFile'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Create/Update Log Query Alert Rules in rg-AvayaAura-pp-001
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    subscriptionId: '$(subscriptionId)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-AvayaAura-pp-001'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/projects/monitoring-rg-AvayaAura-pp-001.bicep'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployBicepFile'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Create/Update Log Query Alert Rules in rg-menanettest-ts-001
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    subscriptionId: '$(subscriptionId)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-menanettest-ts-001'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/projects/monitoring-rg-menanettest-ts-001.bicep'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployBicepFile'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Create/Update Log Query Alert Rules in rg-uaen-tempprint-ts-001
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    subscriptionId: '$(subscriptionId)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-uaen-tempprint-ts-001'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/projects/monitoring-rg-uaen-tempprint-ts-001.bicep'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployBicepFile'
